title = "nanivr"
baseURL = "https://nanivr.github.io"
languageCode = "en-gb"
theme = "ananke-old"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 1
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Be where you want to be"
  facebook = ""
  twitter = "https://twitter.com/nanivrtech "
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  background_color_class = "bg-black"
  featured_image = "/images/ice-drone.jpg"
  recent_posts_number = 2
